sudo: false
language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
go_import_path: github.com/gogs/git-module

env:
  - GO111MODULE=on

install:
  - go get -t -v ./...

script:
  - go test -v -race -verbose -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
