version: "{build}"
skip_tags: true
clone_folder: c:\github.com\gogs\git-module
clone_depth: 1

environment:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org

build: false
deploy: false

install:
  - go version
  - go env
  - go test -v -cover -race -verbose